version: '2'
services:

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
            
    kafka:
        image: "wurstmeister/kafka"
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_CREATE_TOPICS: "QuickFeedTopic:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_BROKER_ID: 0
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    bootkafkapublisher:
        image: r82anand/bootkafkapublisher
        depends_on: 
            - zookeeper
            - kafka
        ports:
            - "31011:31011"
        links:
            - kafka:kafka
            - zookeeper:zookeeper

    bootkafkaclient:
        image: r82anand/bootkafkaclient
        depends_on: 
            - zookeeper
            - kafka
            - bootkafkapublisher
        ports:
            - "31022:31022"
        links:
            - kafka:kafka
            - zookeeper:zookeeper
            - bootkafkapublisher:bootkafkapublisher

